name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker build --tag paradigmxyz/flood:latest .
      - run: docker run --rm paradigmxyz/flood:latest version
      - run: |
          docker run --rm paradigmxyz/flood:latest \
          eth_getBlockByNumber \
          node1=https://eth.llamarpc.com \
          node2=https://eth.llamarpc.com \
          --duration 3 --rate 1
