name: Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    strategy:
      matrix:
        test: ["eth_getBalance", "eth_getBlockByNumber"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker build --tag paradigmxyz/flood:latest .
      - run: docker run --rm paradigmxyz/flood:latest version
      - name: ${{ matrix.test }}
        run: |
          docker run --rm paradigmxyz/flood:latest \
          ${{ matrix.test }} \
          node1=https://eth.llamarpc.com \
          --duration 3 --rate 1
